! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.0
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.

! ---------------------------------------------------------------
! Programmer(s): Auto-generated by swig.
! ---------------------------------------------------------------
! SUNDIALS Copyright Start
! Copyright (c) 2002-2024, Lawrence Livermore National Security
! and Southern Methodist University.
! All rights reserved.
!
! See the top-level LICENSE and NOTICE files for details.
!
! SPDX-License-Identifier: BSD-3-Clause
! SUNDIALS Copyright End
! ---------------------------------------------------------------

module fsundials_cuda_policies_mod
 use, intrinsic :: ISO_C_BINDING
 use fsundials_core_mod
 implicit none
 private

 ! DECLARATION CONSTRUCTS

 integer, parameter :: swig_cmem_own_bit = 0
 integer, parameter :: swig_cmem_rvalue_bit = 1
 integer, parameter :: swig_cmem_const_bit = 2
 type, bind(C) :: SwigClassWrapper
  type(C_PTR), public :: cptr = C_NULL_PTR
  integer(C_INT), public :: cmemflags = 0
 end type
 type, public :: SWIGTYPE_p_cudaStream_t
  type(SwigClassWrapper), public :: swigdata
 end type
 public :: FThreadDirectExecPolicy_new
 public :: FGridStrideExecPolicy_new
 public :: FBlockReduceExecPolicy_new
 public :: FBlockReduceAtomicExecPolicy_new

! WRAPPER DECLARATIONS
interface
function swigc_FThreadDirectExecPolicy_new(farg1, farg2) &
bind(C, name="_wrap_FThreadDirectExecPolicy_new") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_SIZE_T), intent(in) :: farg1
integer(C_INTPTR_T) :: farg2
type(C_PTR) :: fresult
end function
            
function swigc_FGridStrideExecPolicy_new(farg1, farg2, farg3) &
bind(C, name="_wrap_FGridStrideExecPolicy_new") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_SIZE_T), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
integer(C_INTPTR_T) :: farg3
type(C_PTR) :: fresult
end function

function swigc_FBlockReduceExecPolicy_new(farg1, farg2, farg3) &
bind(C, name="_wrap_FBlockReduceExecPolicy_new") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_SIZE_T), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
integer(C_INTPTR_T) :: farg3
type(C_PTR) :: fresult
end function

function swigc_FBlockReduceAtomicExecPolicy_new(farg1, farg2, farg3) &
bind(C, name="_wrap_FBlockReduceAtomicExecPolicy_new") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
integer(C_SIZE_T), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
integer(C_INTPTR_T) :: farg3
type(C_PTR) :: fresult
end function


end interface

contains
 ! MODULE SUBPROGRAMS
function FThreadDirectExecPolicy_new(blockdim, stream) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
use cudafor
type(C_PTR) :: swig_result
integer(C_SIZE_T), intent(in) :: blockdim
integer(kind=cuda_stream_kind), intent(in) :: stream
type(C_PTR) :: fresult 
integer(C_SIZE_T) :: farg1 
integer(C_INTPTR_T) :: farg2 

farg1 = blockdim
farg2 = stream
fresult = swigc_FThreadDirectExecPolicy_new(farg1, farg2)
swig_result = fresult
end function

function FGridStrideExecPolicy_new(blockdim, griddim, stream) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
use cudafor
type(C_PTR) :: swig_result
integer(C_SIZE_T), intent(in) :: blockdim
integer(C_SIZE_T), intent(in) :: griddim
integer(kind=cuda_stream_kind), intent(in) :: stream
type(C_PTR) :: fresult 
integer(C_SIZE_T) :: farg1 
integer(C_SIZE_T) :: farg2 
integer(C_INTPTR_T) :: farg3 

farg1 = blockdim
farg2 = griddim
farg3 = stream
fresult = swigc_FGridStrideExecPolicy_new(farg1, farg2, farg3)
swig_result = fresult
end function

function FBlockReduceExecPolicy_new(blockdim, griddim, stream) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
use cudafor
type(C_PTR) :: swig_result
integer(C_SIZE_T), intent(in) :: blockdim
integer(C_SIZE_T), intent(in) :: griddim
integer(kind=cuda_stream_kind), intent(in) :: stream
type(C_PTR) :: fresult 
integer(C_SIZE_T) :: farg1 
integer(C_SIZE_T) :: farg2 
integer(C_INTPTR_T) :: farg3 

farg1 = blockdim
farg2 = griddim
farg3 = stream
fresult = swigc_FBlockReduceExecPolicy_new(farg1, farg2, farg3)
swig_result = fresult
end function

function FBlockReduceAtomicExecPolicy_new(blockdim, griddim, stream) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
use cudafor
type(C_PTR) :: swig_result
integer(C_SIZE_T), intent(in) :: blockdim
integer(C_SIZE_T), intent(in) :: griddim
integer(kind=cuda_stream_kind), intent(in) :: stream
type(C_PTR) :: fresult 
integer(C_SIZE_T) :: farg1 
integer(C_SIZE_T) :: farg2 
integer(C_INTPTR_T) :: farg3 

farg1 = blockdim
farg2 = griddim
farg3 = stream
fresult = swigc_FBlockReduceAtomicExecPolicy_new(farg1, farg2, farg3)
swig_result = fresult
end function


end module
